# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'InfinitumScrollView' do

pod 'MJExtension', '~> 3.0.10'
pod 'Masonry', '~> 1.0.0'
pod 'SDWebImage', '~> 3.7.6'

end

